# 植物画像解析のためのcolaboratoryの基本的な使い方

## はじめに
- Google Colaboratoryで植物画像解析を行う場合における基礎的な操作について紹介します。

- PythonおよびColaboratoryについて経験のある方は本稿を飛ばしてもらっても構いません。

- **Google Chome**を利用してこの画面を開いていますか？他のブラウザでも実行可能ですが、一部の機能が正常に実行されなかったり、挙動が異なることがあります。

- 入れていない場合は、[Google Chromeをダウンロードしてインストール](https://www.google.com/intl/ja_jp/chrome/)　してからこのURLを開いてください。

- Google Colaboratoryの一般的な使い方を学習したい人は[公式のノートブック](https://colab.research.google.com/notebooks/welcome.ipynb?hl=ja)を参照しましょう。

このノートブック（ハンズオン資料）を、自分のgoogle driveの中に保存してください。画面上部の**ファイルをクリックし、ドライブにコピーを保存**を選択します。新しいタブが立ち上がりますので、古い方は閉じておきましょう。コピーしなくても実行可能ですが、機能が制限されます。

自分でコードを書き換えてしまった結果、正常に実行しなくなって戻せなくなった場合はこのノートブックを再コピーすれば最初から始めることができます。

途中からコードを実行したりセルの実行を飛ばすとエラーが起きることがあります。何をやっているか自信がない人は、上から順番に実行していきましょう。

## pyhtonの基礎その１

In [1]:
# pythonでは行頭に半角の「#」を挿入する事で
# プログラムには関係ないコメント行（メモや説明）として扱うことができます。
# それ以外の行は全てコードとして処理されます。

In [2]:
# 基本。プリントで任意の情報を出力します。

print("hello world!")

hello world!


In [5]:
# エラーが出たら落ち着いてエラーメッセージを確認し、原因を理解しましょう
print hello world!

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(hello world!)? (<ipython-input-5-5022060e55cf>, line 2)

In [6]:
# 変数の代入と利用。aの値を変えてどうなるか試してみましょう。
a = 0

print(a)  # 変数の場合は""がいりません。
print("aの中身は", a, "です")  # カンマで区切ると一行に複数の情報を記載できます。

0
aの中身は 0 です


In [8]:
# 変数の種類
v = 1  # 整数 , int integerの略。
v = "a"  # 文字 , str stringの略。 "" or ''で囲む
v = True  # 論理値 , bool　booleanの略。 True or False

In [9]:
# リスト
v = [1,3,5]
print(v[0])  # Pythonではリストの最初は０で始まるので注意しましょう。
print(v[1])
print(v[2])

1
3
5


In [10]:
print(v[3])  # ４番目はないのでこの行でエラーになる。

IndexError: list index out of range

In [11]:
# リストの末尾に要素を加える
v.append(20)
print(v)

# 更新されたvの値は保存されるので、このセルを実行するたびに増えていきます

[1, 3, 5, 20]


In [12]:
# 変数の計算。a、bの値を変えてどうなるかためしてみましょう。
a = -2
b = 3
print("a+b is",a+b)
print("a-b is", a-b)
print("a*b is", a*b)
print("a/b is", a/b)

a += 1  # +=1とは1を加算する事です
# a = a + 1
print(a)

a+b is 1
a-b is -5
a*b is -6
a/b is -0.6666666666666666
-1


In [13]:
# 結果は違う変数に代入できます。
a=1
b=2
c=a+b
print(c)

3


In [14]:
#一度代入された変数はこのノートブックを再起動するか、代入しなおすまで保持されます。
print(a)

1


In [15]:
# pythonの世界では「=」は代入を意味します。
# 等号記号は「==」になります。
a=1
b=2
print(a==b)  # a is not equal to bなので falseをかえします。


a=1
b=1
print(a==b)  # true


False
True


In [16]:
# 条件分岐。aの値を変えてどうなるか試してみましょう。
# ちなみにifの中はタブもしくはスペース４つ分です。
a = 2

if a > 2:
    print("aは２よりも大きい")
elif a == 2:  # ifではなくて、もし〜〜ならば、
    print("aは２と等しい")
else:  # もし上記条件のいずれにもあてはまなければ、
    print("aは２よりも小さい")

aは２と等しい


In [17]:
# くりかえし処理の表現方法です。条件を満たす限り、whileの処理を繰り返します。

a=-1
while a < 10:  # aが10未満の間、下の処理を繰り返す。
    print("aは", a, "です")
    a+=1  # aに１加算します。
print("aは10に達しました")

aは -1 です
aは 0 です
aは 1 です
aは 2 です
aは 3 です
aは 4 です
aは 5 です
aは 6 です
aは 7 です
aは 8 です
aは 9 です
aは10に達しました


In [18]:
# 繰り返し処理2
a = [1,20,300,500]  # リスト
for n in a:
    print(n)

1
20
300
500


In [19]:
# enumerateを使うことで何番目の要素か同時に取得することができます。

for i, n in enumerate(a):
    print(i, "番目の値は", n)

0 番目の値は 1
1 番目の値は 20
2 番目の値は 300
3 番目の値は 500


In [17]:
# len()を使うことでリストの長さを取得することができます。
a = [1,20,300,500]
print(len(a))

# forと組み合わせることもできます。
a = [1,20,300,500]
# len(a)は4なので、range(4)は0,1,2,3を返します。
for i in range(len(a)):
    print(i, "番目の値は", a[i])

4
0 番目の値は 1
1 番目の値は 20
2 番目の値は 300
3 番目の値は 500


## pythonの基礎その２

In [20]:
# 関数の定義と利用
# pythonは基本上から一行ずつ順番に実行されていきますが、関数は定義しても呼び出されるまで動きません。

def add(x):  # defはdefine,　xは引数（ひきすう）。
    x += 1
    return x  # return ~~は戻り値


def subtract(x,y): #引数は複数指定できます。
    z = x - y
    return z


def add_and_subtract(x,y): #戻り値も複数指定できます。
    z1 = x + y
    z2 = x - y
    return z1, z2


def noreturn(z):
    print ("関数noreturnに入力されたデータは",z,"です") #戻り値のない関数も定義できます。

In [21]:
a= add(1) #simple関数に1を入れると、関数内で1に1を加算して、2を返します。
print(a)

2


In [23]:
a = subtract(1,2)  # subtract関数に1と2を入れると、関数内で1-2を計算して、-1を返します。
print(a)

z1,z2 = add_and_subtract(1,2)  # add_and_subtract関数に1と2を入れると、関数内で1+2と1-2を計算して、3と-1を返します。
print(z1, z2)

noreturn(2)  # noreturn関数に2を入れると、戻り値はありませんが、関数内でprintされます。

-1
3 -1
関数noreturnに入力されたデータは 2 です


In [23]:
# プログラムが大きくなり、変数と関数が増えたり冗長的になると全体像が把握しにくくなります。「クラス」を利用しましょう。

class Plant:
    # クラスの中には変数と関数を定義できます。
    # このクラスの中に定義された変数は「プロパティ」、関数は「メソッド」と呼ばれます。
    # クラスの中に定義された変数と関数は「クラス変数」と「クラスメソッド」と呼ばれます。
    def __init__(self):
        # __init__はクラスの初期化を行う関数です。
        # クラスを利用する際に、この関数が自動的に実行されます。
        self.plantation_date = ''
        self.biomass = ''
        self.height = ''        
    def get_info(self):
        # クラスの中に定義された関数は、第一引数にselfを指定する必要があります。
        # selfはクラス自身を指します。
        # self.変数名でクラス変数を利用できます。
        message = "planted in {}, biomass is {}, height is {}".format(self.plantation_date, self.biomass, self.height)
        return message

In [26]:
# 自身でクラスを定義することは少々難しいかもしれません。
# クラスの利用方法のみを理解するだけでも最初は十分です。
rice = Plant()
rice.plantation_date = '2018/5/1'
rice.biomass = 1.2
rice.height = 10

corn = Plant()
corn.plantation_date = '2018/5/1'
corn.biomass = 2.1
corn.height = 50


print(rice.get_info())
print(corn.get_info())


planted in 2018/5/1, biomass is 1.2, height is 10
planted in 2018/5/1, biomass is 2.1, height is 50


In [ ]:
# クラスを使わなければ変数を階層構造無しでそれぞれ定義しなければなりません。
# 変数が増えると管理が大変になります。

rice_plantation_date = '2018/5/1'
rice_biomass = 1.2
rice_height = 10

corn_plantation_date = '2018/5/1'
corn_biomass = 2.1
corn_height = 50

## pythonの基礎その３

pythonでは関数やクラスを定義し、駆使することで、プログラムを簡潔に記述することができます。しかしながら、必要な機能をすべて自分で定義するのは大変です。そのようなことをしなくても、pythonには標準で多くのライブラリが用意されています。それらを利用するには「import」を利用します。

In [8]:
# 例えばdatetimeというライブラリを使うと、日付の計算が簡単にできます。
# このライブラリは標準で入っているので、インストールは不要です。
import datetime
today = datetime.date.today()
print(today)
# 今日から10日後の日付を計算する。
ten_days_later = today + datetime.timedelta(days=10)
print(ten_days_later)
# 時間も取得できます。
now = datetime.datetime.now()
print(now)

2023-11-04
2023-11-14
2023-11-04 10:21:02.515728


数値計算にはnumpyというライブラリをインポートし、利用することが多いです。
```python
import numpy as np
a = np.array([1,2,3])
print(a)  # [1 2 3]
```
import numpyとしても使用できますが、下のように文字数が増えるので、npという別名をつけて利用することが多いです。
```python
import numpy
a = numpy.array([1,2,3])
print(a)  # [1 2 3]
```

画像は３次元配列で表現され、必ずといっていいほど使われるので、numpyの使い方は覚えておきましょう。

In [11]:
import numpy as np
a = np.array([1,2,3,4,5])  # numpyのarrayという関数を利用して、リストをnumpyの配列に変換します。

# リストと異なり、numpyの配列は数値計算に特化しているので、合計や平均などの計算が簡単にできます。
print(a)
print(np.sum(a))  # sumは合計を意味します。
print(np.mean(a))  # meanは平均を意味します。
print(np.median(a))  # medianは中央値を意味します。
print(np.std(a))  # stdは標準偏差を意味します。
print(np.sqrt(a))  # sqrtは平方根を意味します。
print(np.log(a))  # logは自然対数を意味します。
print(np.exp(a))  # expは指数関数を意味します。

print(a.shape)  # shapeは配列の形状を意味します。
print(a.dtype)  # dtypeは配列のデータ型を意味します。
print("_______")

# 多次元配列の作成
image = np.zeros((32,32,3), dtype=np.uint8)  # 32x32のRGB画像を作成します。
print(image.shape)  
print(image.dtype)


[1 2 3 4 5]
15
3.0
3.0
1.4142135623730951
[1.         1.41421356 1.73205081 2.         2.23606798]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
(5,)
int64
_______
(32, 32, 3)
uint8


## フォルダ・ファイル操作

## マジックコマンド（Colaboratoryのみ）の活用

In [14]:
# Colaboratoy (Jupyter Notebook)では、シェルコマンドを実行することができます。
# シェルコマンドとは、コマンドプロンプトやターミナルで実行するコマンドのことです。
# 例えば、lsコマンドはファイル一覧を表示するコマンドです。
!ls


PlantServation.ipynb                   globalwheat2021.ipynb
WEIPS.ipynb                            imgs
_rice_seed_shape_analysis copy.ipynb   plantseg.ipynb
apple_leaf.ipynb                       plantvilllage.ipynb
assets                                 pollencounter.ipynb
basics.ipynb                           rice_seed_shape_analysis.ipynb
chronoroot.ipynb                       riceyieldcnn.ipynb
dayflower_stomata_quantification.ipynb sai.ipynb
env_data_analysis.ipynb                u2netp.ipynb
