# Pythonの基本的な使い方

## はじめに
- Python言語の基礎的な操作について紹介します。

- Python言語のすべてをカバーする基礎的ハンズオンではありません。

- それでもなお、PythonおよびColaboratoryについて経験のある方は本稿を飛ばしてもらっても構いません。

- **Google Chome**を利用してこの画面を開いていますか？他のブラウザでも実行可能ですが、一部の機能が正常に実行されなかったり、挙動が異なることがあります。

- インストールしていない場合は、[Google Chromeをダウンロードしてインストール](https://www.google.com/intl/ja_jp/chrome/)　してからこのURLを開いてください。

- Google Colaboratoryの一般的な使い方を学習したい人は[公式のノートブック](https://colab.research.google.com/notebooks/welcome.ipynb?hl=ja)を参照しましょう。

このノートブック（ハンズオン資料）を、自分のgoogle driveの中に保存してください。画面上部の**ファイルをクリックし、ドライブにコピーを保存**を選択します。新しいタブが立ち上がりますので、古い方は閉じておきましょう。コピーしなくても実行可能ですが、機能が制限されます。

自分でコードを書き換えてしまった結果、正常に実行しなくなって戻せなくなった場合はこのノートブックを再コピーすれば最初から始めることができます。

途中からコードを実行したりセルの実行を飛ばすとエラーが起きることがあります。何をやっているか自信がない人は、上から順番に実行していきましょう。

## 基礎

In [ ]:
# pythonでは行頭に半角の「#」を挿入する事で
# プログラムには関係ないコメント行（メモや説明）として扱うことができます。
# それ以外の行は全てコードとして処理されます。

In [ ]:
# 基本。プリントで任意の情報を出力します。

print("hello world!")

hello world!


In [ ]:
# エラーが出たら落ち着いてエラーメッセージを確認し、原因を理解しましょう
print hello world!

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(hello world!)? (<ipython-input-5-5022060e55cf>, line 2)

In [ ]:
# 変数の代入と利用。aの値を変えてどうなるか試してみましょう。
a = 0

print(a)  # 変数の場合は""がいりません。
print("aの中身は", a, "です")  # カンマで区切ると一行に複数の情報を記載できます。

0
aの中身は 0 です


In [ ]:
# 変数の種類
v = 1  # 整数 , int integerの略。
v = "a"  # 文字 , str stringの略。 "" or ''で囲む
v = True  # 論理値 , bool　booleanの略。 True or False

In [ ]:
# 変数の計算。a、bの値を変えてどうなるかためしてみましょう。
a = -2
b = 3
print("a+b is",a+b)
print("a-b is", a-b)
print("a*b is", a*b)
print("a/b is", a/b)

a += 1  # +=1とは1を加算する事です
# a = a + 1
print(a)

a+b is 1
a-b is -5
a*b is -6
a/b is -0.6666666666666666
-1


In [32]:
# 結果は違う変数に代入できます。
a = 1
b = 2
c = a+b
print(c)

3


In [34]:
# 他にも剰余を示す%記号も演算子としてよく使われます。
a = 10
b = 3

print(a%b)

1


In [35]:
#一度代入された変数はこのノートブックを再起動するか、代入しなおすまで保持されます。
print(a)

10


In [ ]:
# リスト
v = [1,3,5]
print(v[0])  # Pythonではリストの最初は０で始まるので注意しましょう。
print(v[1])
print(v[2])

1
3
5


In [ ]:
print(v[3])  # ４番目はないのでこの行でエラーになる。

IndexError: list index out of range

In [ ]:
# リストの末尾に要素を加える
v.append(20)
print(v)

# 更新されたvの値は保存されるので、このセルを実行するたびに増えていきます

[1, 3, 5, 20]


In [59]:
# 辞書
d = {}
# 辞書はkeyとvalueというペアでデータを管理します。
d["temperature"] = 36.8
d["humidity"] = 80

print(d)

# 辞書の値はキーでアクセスすることができます。
print(d["temperature"])


{'temperature': 36.8, 'humidity': 80}
36.8


In [ ]:
# pythonの世界では「=」は代入を意味します。
# 等号記号は「==」になります。
a=1
b=2
print(a==b)  # a is not equal to bなので falseをかえします。


a=1
b=1
print(a==b)  # true


False
True


In [ ]:
# 条件分岐。aの値を変えてどうなるか試してみましょう。
# ちなみにifの中はタブもしくはスペース４つ分です。
a = 2

if a > 2:
    print("aは２よりも大きい")
elif a == 2:  # ifではなくて、もし〜〜ならば、
    print("aは２と等しい")
else:  # もし上記条件のいずれにもあてはまなければ、
    print("aは２よりも小さい")

aは２と等しい


In [ ]:
# くりかえし処理の表現方法です。条件を満たす限り、whileの処理を繰り返します。

a=-1
while a < 10:  # aが10未満の間、下の処理を繰り返す。
    print("aは", a, "です")
    a+=1  # aに１加算します。
print("aは10に達しました")

aは -1 です
aは 0 です
aは 1 です
aは 2 です
aは 3 です
aは 4 です
aは 5 です
aは 6 です
aは 7 です
aは 8 です
aは 9 です
aは10に達しました


In [ ]:
# 繰り返し処理2
a = [1,20,300,500]  # リスト
for n in a:
    print(n)

1
20
300
500


In [ ]:
# enumerateを使うことで何番目の要素か同時に取得することができます。

for i, n in enumerate(a):
    print(i, "番目の値は", n)

0 番目の値は 1
1 番目の値は 20
2 番目の値は 300
3 番目の値は 500


In [ ]:
# len()を使うことでリストの長さを取得することができます。
a = [1,20,300,500]
print(len(a))

# forと組み合わせることもできます。
a = [1,20,300,500]
# len(a)は4なので、range(4)は0,1,2,3を返します。
for i in range(len(a)):
    print(i, "番目の値は", a[i])

4
0 番目の値は 1
1 番目の値は 20
2 番目の値は 300
3 番目の値は 500


## 関数とクラス

In [ ]:
# 関数の定義と利用
# pythonは基本上から一行ずつ順番に実行されていきますが、関数は定義しても呼び出されるまで動きません。

def add(x):  # defはdefine,　xは引数（ひきすう）。
    x += 1
    return x  # return ~~は戻り値


def subtract(x,y): #引数は複数指定できます。
    z = x - y
    return z


def add_and_subtract(x,y): #戻り値も複数指定できます。
    z1 = x + y
    z2 = x - y
    return z1, z2


def noreturn(z):
    print ("関数noreturnに入力されたデータは",z,"です") #戻り値のない関数も定義できます。

In [ ]:
a= add(1) #simple関数に1を入れると、関数内で1に1を加算して、2を返します。
print(a)

2


In [ ]:
a = subtract(1,2)  # subtract関数に1と2を入れると、関数内で1-2を計算して、-1を返します。
print(a)

z1,z2 = add_and_subtract(1,2)  # add_and_subtract関数に1と2を入れると、関数内で1+2と1-2を計算して、3と-1を返します。
print(z1, z2)

noreturn(2)  # noreturn関数に2を入れると、戻り値はありませんが、関数内でprintされます。

-1
3 -1
関数noreturnに入力されたデータは 2 です


In [ ]:
# プログラムが大きくなり、変数と関数が増えたり冗長的になると全体像が把握しにくくなります。「クラス」を利用しましょう。

class Plant:
    # クラスの中には変数と関数を定義できます。
    # このクラスの中に定義された変数は「プロパティ」、関数は「メソッド」と呼ばれます。
    # クラスの中に定義された変数と関数は「クラス変数」と「クラスメソッド」と呼ばれます。
    def __init__(self):
        # __init__はクラスの初期化を行う関数です。
        # クラスを利用する際に、この関数が自動的に実行されます。
        self.plantation_date = ''
        self.biomass = ''
        self.height = ''
    def get_info(self):
        # クラスの中に定義された関数は、第一引数にselfを指定する必要があります。
        # selfはクラス自身を指します。
        # self.変数名でクラス変数を利用できます。
        message = "planted in {}, biomass is {}, height is {}".format(self.plantation_date, self.biomass, self.height)
        return message

In [ ]:
# 自身でクラスを定義することは少々難しいかもしれません。
# クラスの利用方法のみを理解するだけでも最初は十分です。
rice = Plant()
rice.plantation_date = '2018/5/1'
rice.biomass = 1.2
rice.height = 10

corn = Plant()
corn.plantation_date = '2018/5/1'
corn.biomass = 2.1
corn.height = 50


print(rice.get_info())
print(corn.get_info())


planted in 2018/5/1, biomass is 1.2, height is 10
planted in 2018/5/1, biomass is 2.1, height is 50


In [ ]:
# クラスを使わなければ変数を階層構造無しでそれぞれ定義しなければなりません。
# 変数が増えると管理が大変になります。

rice_plantation_date = '2018/5/1'
rice_biomass = 1.2
rice_height = 10

corn_plantation_date = '2018/5/1'
corn_biomass = 2.1
corn_height = 50

## ライブラリの使い方
pythonでは関数やクラスを定義し、駆使することで、プログラムを簡潔に記述することができます。しかしながら、必要な機能をすべて自分で定義するのは大変です。そのようなことをしなくても、pythonには標準で多くのライブラリが用意されています。それらを利用するには「import」を利用します。

In [ ]:
# 例えばdatetimeというライブラリを使うと、日付の計算が簡単にできます。
# このライブラリは標準で入っているので、インストールは不要です。
import datetime
today = datetime.date.today()
print(today)
# 今日から10日後の日付を計算する。
ten_days_later = today + datetime.timedelta(days=10)
print(ten_days_later)
# 時間も取得できます。
now = datetime.datetime.now()
print(now)

2023-11-04
2023-11-14
2023-11-04 10:21:02.515728


数値計算にはnumpyというライブラリをインポートし、利用することが多いです。
```python
import numpy as np
a = np.array([1,2,3])
print(a)  # [1 2 3]
```
import numpyとしても使用できますが、下のように文字数が増えるので、npという別名をつけて利用することが多いです。
```python
import numpy
a = numpy.array([1,2,3])
print(a)  # [1 2 3]
```

画像は３次元配列で表現され、必ずといっていいほど使われるので、numpyの使い方は覚えておきましょう。

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5])  # numpyのarrayという関数を利用して、リストをnumpyの配列に変換します。

# リストと異なり、numpyの配列は数値計算に特化しているので、合計や平均などの計算が簡単にできます。
print(a)
print(np.sum(a))  # sumは合計を意味します。
print(np.mean(a))  # meanは平均を意味します。
print(np.median(a))  # medianは中央値を意味します。
print(np.std(a))  # stdは標準偏差を意味します。
print(np.sqrt(a))  # sqrtは平方根を意味します。
print(np.log(a))  # logは自然対数を意味します。
print(np.exp(a))  # expは指数関数を意味します。

print(a.shape)  # shapeは配列の形状を意味します。
print(a.dtype)  # dtypeは配列のデータ型を意味します。
print("_______")

# 多次元配列の作成
image = np.zeros((32,32,3), dtype=np.uint8)  # 32x32のRGB画像を作成します。
print(image.shape)
print(image.dtype)


[1 2 3 4 5]
15
3.0
3.0
1.4142135623730951
[1.         1.41421356 1.73205081 2.         2.23606798]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
(5,)
int64
_______
(32, 32, 3)
uint8


## ファイル読み込み・書き込み
with open(~, ~) as f:でファイルを読み込んだり、書き込んだりすることができます。
下のセルを実行後、画面左のディレクトリ更新ボタン（ブラウザの更新ボタンではありません）を押すか、しばらくまつとtemp.txtというファイルが生成されることを確認してください。

In [12]:
# ファイルの書き出し

# \nは改行コードです。
test_file = "temp.txt"
with open(test_file, "w") as f:  # wは書き込みモードを意味します。
    f.write("this is test text\n")
    f.write("second line")

In [15]:
# ファイルの読み込み
with open(test_file, "r") as f:  # rは読み込みモードを意味します。
    line = f.read()
    print(line)

this is test text
second line


上記のような方法でファイルを操作する場合、他にもf.writelines(~)、f.readlines()などリストとして扱うなどのアプローチもあります。調べてみてください。


ところで、実際には下のようにcsvやpandasの機能を使うことが（植物画像解析）コーディングの現場では多いものの、pythonの基本ですので覚えてください。pandasを利用したデータフレーム操作については別章で扱います。

In [18]:
# csvファイルを扱う場合はcsvライブラリやpandasを使うことがあります。
import csv

csv_path = "/content/sample_data/california_housing_test.csv"

with open(csv_path, 'r') as file:
    reader = csv.reader(file)
    for i, row in enumerate(reader):
        print(row)
        if i == 3:  # ４行分出力したら止める
            break

['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income', 'median_house_value']
['-122.050000', '37.370000', '27.000000', '3885.000000', '661.000000', '1537.000000', '606.000000', '6.608500', '344700.000000']
['-118.300000', '34.260000', '43.000000', '1510.000000', '310.000000', '809.000000', '277.000000', '3.599000', '176500.000000']
['-117.810000', '33.780000', '27.000000', '3589.000000', '507.000000', '1484.000000', '495.000000', '5.793400', '270500.000000']


In [20]:
import pandas as pd

df = pd.read_csv(csv_path)
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0   
1       -118.30     34.26                43.0       1510.0           310.0   
2       -117.81     33.78                27.0       3589.0           507.0   
3       -118.36     33.82                28.0         67.0            15.0   
4       -119.67     36.33                19.0       1241.0           244.0   
...         ...       ...                 ...          ...             ...   
2995    -119.86     34.42                23.0       1450.0           642.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   
2997    -119.70     36.30                10.0        956.0           201.0   
2998    -117.12     34.10                40.0         96.0            14.0   
2999    -119.63     34.42                42.0       1765.0           263.0   

      population  households  median_income  median_house_value  
0         1537.0       606.0         6.6085            344700.0  
1          809.0       277.0         3.5990            176500.0  
2         1484.0       495.0         5.7934            270500.0  
3           49.0        11.0         6.1359            330000.0  
4          850.0       237.0         2.9375             81700.0  
...          ...         ...            ...                 ...  
2995      1258.0       607.0         1.1790            225000.0  
2996      3496.0      1036.0         3.3906            237200.0  
2997       693.0       220.0         2.2895             62000.0  
2998        46.0        14.0         3.2708            162500.0  
2999       753.0       260.0         8.5608            500001.0  

[3000 rows x 9 columns]

## リスト内包表記
例えば[1,2,3,4,5,6]というリストに対し、

1. それぞれの要素を２倍したリストを作りたい。

2. 偶数のみを抽出したリストを作りたい。

という場合、これまでのハンズオンで記載した方法のみで実現すると下記のようなコードを実装する必要があります。

In [41]:
# ２倍操作
a = [1,2,3,4,5,6]
b = []  # 空のリスト

for value in a:
    b.append(value * 2)
print(b)

# 偶数のみ抽出
c = []  # 空のリスト

for value in a:
    if value % 2 == 0: # ２で割ったときの剰余が０の場合
        c.append(value)
print(c)

[2, 4, 6, 8, 10, 12]
[2, 4, 6]


一方、リスト内包表記を使うともっと簡潔に書くことができます。xはなんでもよいですが、混乱を避けるため、元の変数と重複しないように注意してください。

```python
# 基本形
[x for x in some_list]
# 個々の要素に操作
[x + 1 for x in some_list]
# 条件によるフィルタリング
[x for x in some_list if x > 0]
```


In [42]:
a = [1,2,3,4,5,6]

# 2倍
b = [2*x for x in a]
print(b)

# 偶数のみ
c = [x for x in a if x%2 == 0]
print(c)


[2, 4, 6, 8, 10, 12]
[2, 4, 6]


## フォルダ・ファイル・ディレクトリ操作


In [23]:
import os

# 指定ディレクトリにあるフォルダ一覧をリストとして取得
files = os.listdir("sample_data")
print(files)

['anscombe.json', 'README.md', 'mnist_test.csv', 'california_housing_train.csv', 'california_housing_test.csv', 'mnist_train_small.csv']


In [44]:
# os.path.joinで指定したディレクトリとファイル名を結合して、ファイルのパスを作成する。
# Colaboratoryの作業ディレクトリは/content直下にあるため、
# contentフォルダの中のsample_dataというパスになります。
file = files[0]
path = os.path.join("/content/sample_data", file)
print(file)
print(path)

anscombe.json
/content/sample_data/anscombe.json


In [47]:
# for loopを使えば順次同じ処理を適用させることができます。

for file in files:
    path = os.path.join("/content/sample_data", file)
    print(path)

/content/sample_data/anscombe.json
/content/sample_data/README.md
/content/sample_data/mnist_test.csv
/content/sample_data/california_housing_train.csv
/content/sample_data/california_housing_test.csv
/content/sample_data/mnist_train_small.csv


## マジックコマンドの活用

Colaboratoy (Jupyter Notebook)では、シェルコマンドやColaboratoryの便利機能を活用することができます。


In [50]:
# 現在の作業ディレクトリ（present working directory）
!pwd

/content


In [52]:
# ファイル一覧取得
!ls

sample_data  temp.txt


In [57]:
# フォルダ作成
!mkdir tempfolder
!ls
# フォルダ削除
!rm -r tempfolder
!ls

sample_data  tempfolder  temp.txt
sample_data  temp.txt
